### ISSUE TITLE
Errors when installed on Elgg 3.3.7

### ISSUE THREAD

**Issue by davidspring** [iionly/tidypics#49]
Dear Tidypics developer,
I am using Elgg version 3.3.7 and tried to install the latest version of Tidypics 2.3.6. I renamed the folder and checked the permissions. The plugin installed correctly but when I tried to activate it, I got an error message. Checking the server error log showed the following 13 errors. I understand that a lot of functions in Elgg were changed from version 2 to version 3 due to the need to update to PHP 7. I am hoping that providing this error log will make it a little easier for you to update this important plugin. Here is the error log showing the locations of the 13 errors. 
[10-Jul-2020 10:38:20 America/New_York] [2020-07-10 10:38:20] ELGG.CRITICAL: Exception at time 1594391900:
Error: Call to undefined function get_subtype_id() in /home/ourcommunitynetw/public_html/mod/tidypics/activate.php:10
Stack trace:
#0 /home/ourcommunitynetw/public_html/vendor/elgg/elgg/engine/classes/Elgg/Includer.php(39): require_once()
#1 /home/ourcommunitynetw/public_html/vendor/elgg/elgg/engine/classes/Elgg/Application.php(155): Elgg\Includer::requireFileOnce('/home/ourcommun...')
#2 /home/ourcommunitynetw/public_html/vendor/elgg/elgg/engine/classes/ElggPlugin.php(937): Elgg\Application::requireSetupFileOnce('/home/ourcommun...')
#3 /home/ourcommunitynetw/public_html/vendor/elgg/elgg/engine/classes/ElggPlugin.php(683): ElggPlugin->includeFile('activate.php')
#4 /home/ourcommunitynetw/public_html/vendor/elgg/elgg/actions/admin/plugins/activate.php(26): ElggPlugin->activate()
#5 /home/ourcommunitynetw/public_html/vendor/elgg/elgg/engine/classes/Elgg/Router.php(347): include('/home/ourcommun...')
#6 /home/ourcommunitynetw/public_html/vendor/elgg/elgg/engine/classes/Elgg/Router.php(278): Elgg\Router->getResponseFromFile('/home/ourcommun...', Object(Elgg\Request))
#7 /home/ourcommunitynetw/public_html/vendor/elgg/elgg/engine/classes/Elgg/Router.php(128): Elgg\Router->prepareResponse(Object(Elgg\Http\Request))
#8 /home/ourcommunitynetw/public_html/vendor/elgg/elgg/engine/classes/Elgg/Router.php(104): Elgg\Router->getResponse(Object(Elgg\Http\Request))
#9 /home/ourcommunitynetw/public_html/vendor/elgg/elgg/engine/classes/Elgg/Application.php(473): Elgg\Router->route(Object(Elgg\Http\Request))
#10 /home/ourcommunitynetw/public_html/vendor/elgg/elgg/engine/classes/Elgg/Application.php(359): Elgg\Application->run()
#11 /home/ourcommunitynetw/public_html/vendor/elgg/elgg/engine/classes/Elgg/Application.php(415): Elgg\Application::route(Object(Elgg\Http\Request))
#12 /home/ourcommunitynetw/public_html/index.php(8): Elgg\Application::index()
#13 {main}
 {"exception":"[object] (Error(code: 0): Call to undefined function get_subtype_id() at /home/ourcommunitynetw/public_html/mod/tidypics/activate.php:10)"} {"backtrace":[],"process_id":150057,"memory_peak_usage":"24.46 MB","memory_usage":"24.46 MB","url":"/action/admin/plugins/activate?plugin_guids%5B0%5D=152&__elgg_ts=1594391892&__elgg_token=y2OVOaYeYULqtPoDKOdLSw","ip":"76.121.122.172","http_method":"POST","server":"ourcommunitynetwork.org","referrer":"https://ourcommunitynetwork.org/admin/plugins"}

**Comment by iionly** [comment]
It's not a problem with PHP 7. Tidypics 2.3.6 is for Elgg 2 only (and works fine on PHP 7 with Elgg 2.3). It's just that Tidypics is not yet compatible with Elgg 3 due to a lot of Elgg's own funtion having changed (some removed) and other things that now need to be handled differently. Unfortunately, I had no time yet to work on an updated version of Tidypics for Elgg 3. You could try what rohit1290 made available at https://github.com/rohit1290/tidypics. It's supposed to work on Elgg 3 (I had not even time to test it myself so I can't definitely say that it fully works).

I'll try to make a release for Elgg 3 soon. It's just that other things happened that stopped me from starting the work again and again...
